### ISSUE TITLE
CL_FREQ: New frequencies

### ISSUE THREAD

**Issue by dbarr99** [SDMX-SWG/CDCL#3]

**Comment by brainwasher** [comment]
Related to: https://github.com/SDMX-SWG/CDCL/blob/master/CL_FREQ

**Comment by dbarr99** [comment]
Create annotations for ISO8601 codes. Use exisating SDMX notation for new codes

**Comment by dbarr99** [comment]
SWG agreed on latest CL_FREQ revision during meeting.

**Comment by dbarr99** [comment]
This is in the other issue
